### ISSUE TITLE
Exception: Unexpected keyword argument `disabled`

### ISSUE THREAD

**Issue by vivek-bombatkar** [plotly/dash-recipes#1]
Traceback (most recent call last):
  File "/GIT/testProj_1/dash/test_1.py", line 11, in <module>
    value='test me'
  File "<string>", line 58, in __init__
  File "\Python\Python27\site-packages\dash\development\base_component.py", line 31, in __init__
    ', '.join(sorted(self._prop_names))
Exception: Unexpected keyword argument `disabled`

**Comment by chriddyp** [comment]
I'm not sure what this issue is referring to inside this codebase. Perhaps you meant to open this in the main Dash repo (https://github.com/plotly/dash) or in the community forum: https://community.plot.ly/c/dash

In all issues that you create, please include a simple, reproducable example.
